version: '3'

services:
  mysql:
    image: mysql:8
    container_name: lab-spring-reactive-web-mysql
    cap_add:
      - SYS_NICE
    volumes:
      - "lab-spring-reactive-web-mysql_db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: lab_spring_reactive_web
      TZ: Asia/Taipei
    ports:
      - "3306:3306"

volumes:
  lab-spring-reactive-web-mysql_db:
