DROP TABLE IF EXISTS MESSAGE;
CREATE TABLE MESSAGE
(
    ID SERIAL PRIMARY KEY AUTO_INCREMENT,
    CONTENT VARCHAR(255),
    STATUS INT NOT NULL,
    CREATE_TIME DATETIME(3) DEFAULT (UTC_TIMESTAMP(3)) NOT NULL
);
