version: '3'

services:
  mysql:
    image: mysql:8
    container_name: lab-spring-reactive-web-mysql
    cap_add:
      - SYS_NICE
    sysctls:
      - net.core.somaxconn=32768
      - net.ipv4.tcp_moderate_rcvbuf=1
      - net.ipv4.tcp_no_metrics_save=1
      - net.ipv4.tcp_mtu_probing=1
      - net.ipv4.tcp_timestamps=0
      - net.ipv4.tcp_sack=0
      - net.ipv4.tcp_syncookies=1
      - net.ipv4.tcp_max_syn_backlog=4096
      - net.ipv4.tcp_tw_reuse=1
      - net.ipv4.tcp_fin_timeout=5
      - net.ipv4.tcp_keepalive_time=150
    ulimits:
      nproc: 65535
      nofile:
        soft: 110000
        hard: 1000000
    volumes:
      - "lab-spring-reactive-web-mysql_db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: lab_spring_reactive_web
      TZ: Asia/Taipei
    ports:
      - "3306:3306"
    command:
        --back_log=3500
        --max_connections=100000

volumes:
  lab-spring-reactive-web-mysql_db:
